import type { Metadata } from "next";
import "./globals.css";

import Footer from "@/common/footer/footer";
import Navbar from "@/common/navbar/navbar";
import { Archivo } from "next/font/google";

const archivo = Archivo({
  weight: ["200", "400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className} antialiased base-white-bg`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
